### ISSUE TITLE
[r] Non-iterated `soma_reader` should not return partial results

### ISSUE THREAD

**Issue by mlin** [single-cell-data/TileDB-SOMA#1111]
In `soma_reader()` we've been commanded to read the entire array at once. Currently we take one sip of the straw, and if that's only a partial read, we print a warning but proceed:

https://github.com/single-cell-data/TileDB-SOMA/blob/123cb4370057eb47c5657ca2f846336a86e6032e/apis/r/src/rinterface.cpp#L144-L152

I submit that it's the wrong behavior to return a partial array here, regardless of printing a warning (which might get lost in a long program output). We should do whatever's necessary to read the whole array; if we run out of memory, that's on the caller for having commanded the non-iterated read.

**Comment by johnkerl** [comment]
@eddelbuettel you may have already done some work on this? Sorry for the delay in task assignment ...

**Comment by eddelbuettel** [comment]
I have not and it is not entirely clear what can be done because SOMA(Array)Reader is not fully fleshed out here.

Core resizes and retries. SOMA(Array)Reader does not.  I am not sure what else can be done here _with the current C++ stack_.  We could rewrite our entries in terms of the iterated reader and iterated as needed -- that is about all I can think of.

**Comment by eddelbuettel** [comment]
The old / basic / first pass iterator I wrote does that (modulo not having native iterators ...).  See eg the old test in `test_SOMAReader-Iterated.R`.  Oh, those test files are more candidates for the grande olde renaming part III....

**Comment by johnkerl** [comment]
In Python, Pandas and Arrows have a `.concat` -- is there anything similar we can do in R with `res1` and `res2`?

**Comment by johnkerl** [comment]
@eddelbuettel sorry I didn't read carefully enough.

What I meant was is there some `concat` something for the elements of `rl`. Maybe `rbind` is that thing?

**Comment by johnkerl** [comment]
While in Python we _syntactically_ utter `foo.read().tables().concat()`, I am not asking here for that _syntax_. Only for some _semantic_ way (with R-appropriate syntax) to concatenate the read-batches.

**Comment by eddelbuettel** [comment]
Yes rbind is that thing.  The canonical (old school) use is   `do.call()`  to sweep and operation over a list so here `do.call(rbind, result_list)`.   There various improvements, I happen to like  `dt <- rbindlist(list_of_dts)` which scans the list of `data.table` objects first, computes total sizes, allocates once and injects. Faster and more efficient than the piece-by-piece approach.

**Comment by johnkerl** [comment]
OK @eddelbuettel I have two proposals:

* Get rid of `sdf$read(iterated=FALSE)`. Via vignettes/etc, let anyone who used to use `sdf$read()` know that they should now use `rbind` as you noted above.
* Remove the current implementation of `sdf$read(iterated=FALSE)` and replace it with (mutatis mutandis) what you wrote above:

```
  sdf$read(iterated = TRUE)
  rl <- list()
  while( ! sdf2$read_complete() ) {
    rl <- c(rl, sdf2$read_next())
  }
  return(do.call(rbind, rl))
```

I would prefer the latter.

**Comment by eddelbuettel** [comment]
Ok -- two good things happened today.  One, @bkmartinjr read me the header file out aloud that I should have been aware of.  So with that wave of the cluebat we have more options than the two outlined above!  The second good thing was my bi-annual dentist visit giving me keyboard free on the bycicle to/fro and there to ponder this :smile: 

Now witness:

```r
> sdf3 <- SOMADataFrameOpen(uri, tiledbsoma_ctx = tiledbsoma::SOMATileDBContext$new(c("soma.init_buffer_bytes"="100000000")))
> res3 <- sdf3$read()
> res3
Table
4848644 rows x 3 columns
$soma_dim_0 <int64 not null>
$soma_dim_1 <int64 not null>
$soma_data <float not null>
> 
```

So un-iterated read without error _given a sufficient memory budget_.  So my new proposal is

- keep `read()` as is but because we are a serious project now _error_ when reads are incomplete with an error message indicating both alternates: increasing memory budget, or setting `iterated=TRUE`
- in `read(iterated=TRUE)` hide the handle to the reader, iterate over it and return a list of arrow tables -- this can be refined later too -- and the user gets to loop over the table, materialize if/when she decides is best
- we can later decide to expose the iteration

Thoughts?

**Comment by johnkerl** [comment]
> keep read() as is but because we are a serious project now error when reads are incomplete with an error message indicating both alternates: increasing memory budget, or setting iterated=TRUE

I think this is fine -- morally the same as having the user do an `rbind` over a one-element list

> in read(iterated=TRUE) hide the handle to the reader, iterate over it and return a list of arrow tables -- this can be refined later too -- and the user gets to loop over the table, materialize if/when she decides is best

i think this is not fine -- if the chunk sizes are set by the user to be compatible with (nearly) filling up RAM, they need to be able to get one almost-RAM-filling chunk, do what they need to with it, then get the next almost-RAM-filling chunk, do what they want with it, etc.

**Comment by eddelbuettel** [comment]
Sure. Then we have iteration support in the high-level and they just fail -- or get to do `sr_setup(); while (!sr_complete()) sr_next())` themselves outside the high-level functions (unless we expose this -- but that may differ from what Python has).

The code is all there and works, it really is up to use about how to expose it "best",

**Comment by eddelbuettel** [comment]
Better?

```r
> library(tiledbsoma)
> uri <- "/tmp/tiledb/soco/pbmc3k_processed/ms/RNA/X/data"
> sdf <- SOMADataFrameOpen(uri)
> val <- sdf$read()
Error: Read of '/tmp/tiledb/soco/pbmc3k_processed/ms/RNA/X/data' is incomplete.
Consider increasing the memory allocation via the configuration
option 'soma.init_buffer_bytes', or using iterated partial reads.
> 
```

**Comment by eddelbuettel** [comment]
This has been taken care of in #1194 and can be closed.
