### ISSUE TITLE
[ci/python] Fix nightly Python-packaging CI error

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#1226]
Example: https://github.com/single-cell-data/TileDB-SOMA/actions/runs/4637189029

**Comment by mlin** [comment]
Two issues:

1) #1190 introduced errors into python-packaging.wdl that prevented GitHub from even parsing it. [simple fix](https://github.com/single-cell-data/TileDB-SOMA/commit/2a4d6c9ba122893e646cc5dc511626e0f4f62e2e) to the parsing issue, and we can come back later to see if it actually works on release (not likely, but also not critical since we have the manual procedure).
2) After addressing that, we have a [macOS build issue finding libtiledbsoma](https://github.com/single-cell-data/TileDB-SOMA/actions/runs/4582510978/jobs/8092783111#step:4:332). *Probably* (not certain) introduced by #1189 based on the timelines when the nightly build failure started.

@nguyenv any suggestions come to mind based on [this assert error](https://github.com/single-cell-data/TileDB-SOMA/actions/runs/4582510978/jobs/8092783111#step:4:332)? thanks

**Comment by johnkerl** [comment]
ok both those were caused by me :(

**Comment by johnkerl** [comment]
@nguyenv re the second one I need

```
if(APPLE)
...
endif()
```

but also I need to find out the syntax to ask for using the (now-necessary) compiler flag only for macos version >= 13.0 ... 👀

**Comment by johnkerl** [comment]
https://github.com/single-cell-data/TileDB-SOMA/pull/1235

**Comment by mlin** [comment]
👍 https://github.com/single-cell-data/TileDB-SOMA/actions/runs/4660094399
