### ISSUE TITLE
[r] Improve spec compliance of TileDB-SOMA-R's `read`

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#1285]
We need to negotiate a middle ground between the Python iterator API and a way in R to:

* Get that iteration for when single read chunks fit in RAM but their total size does not
* Feels R-idiomatic for users
* If we can have both, great; if not, the first must win

Tasks

- [x] Implement iterators
- [x] Experiment Axis Query functions `$obs()` `$var()` and `$X()` return iterators

cc @pablo-gar @aaronwolen

**Comment by pablo-gar** [comment]
My take from slack:

The current form of `$read(iterated = TRUE)`  creates all Arrow objects upon the call and stores them in a list which is then returned. IMO this is not ideal because:

- Deviates from the spec and deviates from python behavior.
- The user cannot control iteration at the tiledbsoma level, but only at the R-level on a native list.
- I suspect this behavior leads to heavy processing and memory overhead (I haven’t tested fully).  For medium-size queries on of the Census (~200K cells), the  `$read(iterated = TRUE)`  call of `X` doesn’t finish even after 20 min of running.

I have created a [test branch and draft PR](https://github.com/single-cell-data/TileDB-SOMA/pull/1274/files) (just for testing) that implements the following functionality for `SOMADataFrame`:

- Moves all iteration functionality to a ReadIter and TableReadIter class, fully mimicking the python implementation.
- Adds the concat  method to the iterator and it uses Arrow’s concat_tables()

This is is how it works

```r
> library(tiledbsoma)
> 
> ctx <- tiledbsoma::SOMATileDBContext$new(
+   config = c("soma.init_buffer_bytes" = "3000")
+ )
> 
> experiment = SOMAExperimentOpen("pbmc3k", tiledbsoma_ctx =ctx)
> 
> ###
> # Read all via tildb single call
> experiment$obs$read()
Error: Read of 'file:///Users/pgarcianieto/scripts/repos/TileDB-SOMA/apis/python/notebooks/data/sparse/pbmc3k/obs' is incomplete.
Consider increasing the memory allocation via the configuration
option 'soma.init_buffer_bytes', or using iterated partial reads.
> 
> ###
> # Creates TableReadIter
> iterator <- experiment$obs$read(iterated = TRUE)
> 
> # Iteration 1
> iterator$read_next()
# Table
# 187 rows x 6 columns
# $soma_joinid <int64 not null>
# $obs_id <large_string not null>
# $n_genes <int64 not null>
# $percent_mito <float not null>
# $n_counts <float not null>
# $louvain <large_string not null>
> 
> # Iteration 2
> iterator$read_next()
# Table
# 187 rows x 6 columns
# $soma_joinid <int64 not null>
# $obs_id <large_string not null>
# $n_genes <int64 not null>
# $percent_mito <float not null>
# $n_counts <float not null>
# $louvain <large_string not null>
> 
> # Complete till end
> iterator$read_concat()
# Table
# 2264 rows x 6 columns
# $soma_joinid <int64 not null>
# $obs_id <large_string not null>
# $n_genes <int64 not null>
# $percent_mito <float not null>
# $n_counts <float not null>
# $louvain <large_string not null>
> 
> ###
> # Fully mimics Python API
> results = experiment$obs$read(iterated = TRUE)$read_concat()
> 
> results
# Table
# 2638 rows x 6 columns
# $soma_joinid <int64 not null>
# $obs_id <large_string not null>
# $n_genes <int64 not null>
# $percent_mito <float not null>
# $n_counts <float not null>
# $louvain <large_string not null>
```

**Comment by pablo-gar** [comment]
Completed with https://github.com/single-cell-data/TileDB-SOMA/pull/1505 and https://github.com/single-cell-data/TileDB-SOMA/pull/1274

**Comment by johnkerl** [comment]
@pablo-gar can we close this issue now?

**Comment by pablo-gar** [comment]
Forgot to hit close ...
