### ISSUE TITLE
[Bug]Can't install tiledb-soma R package [bug]

### ISSUE THREAD

**Issue by woodyNsinbad** [single-cell-data/TileDB-SOMA#2931]
**Describe the bug**
I am trying to install tiledb-soma R package by the command in install page 

```shell
Rscript -e 'install.packages("tiledbsoma", repos = c("https://tiledb-inc.r-universe.dev", "https://cloud.r-project.org"))'
```

but I got this error below:

```
 ../inst/include/tiledbsoma_types.h:23:10: fatal error: tiledbsoma/tiledbsoma: No such file or directory
   23 | #include <tiledbsoma/tiledbsoma>
```

**Versions (please complete the following information):**
 - TileDB-SOMA version:  I think the command up there is latest version .
 - Language and language version R 4.4.1
 - OS is Ubuntu
 - Note: you can use `tiledbsoma.show_package_versions()` (Python) or `tiledbsoma::show_package_versions()` (R)

PS : 
 could you please give a work Dockerfile for building R version ~ pls ~~~

**Comment by eddelbuettel** [comment]
Thanks for taking the time to file a bug report.  Several of us at TileDB and CZI actually develop on Ubuntu so this clearly works if you have all components (`git` and `cmake` are required).  I suspect you missed an earlier error message from building the library `libtiledbsoma`.  Depending on the version of Ubuntu you use, you can also get a binary from [r-universe via this page](https://tiledb-inc.r-universe.dev/tiledbsoma).

**Comment by eddelbuettel** [comment]
We support an easy-to-use environment at [TileDB Cloud](https://www.tiledb.com/products/tiledb-cloud) you can try for free -- see for example 'Marketplace'.  

Our CI scripts also hard-code how to build from source as they do this on every commit and merge.  But otherwise, a Dockerfile _can be_ be as minimal as the following which works here on my not-so-current workstation in under six minutes.  It relies on [r2u](https://eddelbuettel.github.io/r2u) for binaries to speed things up, then adds `cmake` and `git` as required for a source build -- and then invokes the command you tried:

```sh
## r2u makes working with R packages easy, fast, reliable; 'jammy' also works
FROM rocker/r2u:noble

RUN apt update -qq \
    && apt install --yes --no-install-recommends cmake git \
    && Rscript -e 'install.packages("tiledbsoma", repos = c("https://tiledb-inc.r-universe.dev", "https://cloud.r-project"))'
```

**Comment by johnkerl** [comment]
Hi @woodyNsinbad ! Seconding a few things:

* Dockerfile info as provided by @eddelbuettel 
* Build info here https://github.com/single-cell-data/TileDB-SOMA/blob/main/apis/r/README.md

But what would be most helpful is if you can please send the entire build output, not just the lines
```
 ../inst/include/tiledbsoma_types.h:23:10: fatal error: tiledbsoma/tiledbsoma: No such file or directory
   23 | #include <tiledbsoma/tiledbsoma>
```
-- feel free to paste the entirety into https://gist.github.com and share the link here.

**Comment by johnkerl** [comment]
Also @woodyNsinbad -- which Ubuntu version are you on?

**Comment by woodyNsinbad** [comment]
thank you so much for the dockerfile. I use docker r-base image for my base image. and I try mamba install base on ubuntu22.04 and it work perfectly. thanks a lot 

> Thanks for taking the time to file a bug report. Several of us at TileDB and CZI actually develop on Ubuntu so this clearly works if you have all components (`git` and `cmake` are required). I suspect you missed an earlier error message from building the library `libtiledbsoma`. Depending on the version of Ubuntu you use, you can also get a binary from [r-universe via this page](https://tiledb-inc.r-universe.dev/tiledbsoma).

**Comment by eddelbuettel** [comment]
Glad you have it working.  We also added a PR to make the possible error more clear, see #2932,  I still suspect your error is due to a lack of `cmake` and `git` which neither of these Docker containers has by default.   It so happens that I am the author of the Docker r-base container, and the rocker/r2u container.  I can only reiterate that you may want to have a look at [r2u](https://eddelbuettel.github.io/r2u).  But of course -- if you prefer mamba that works as well.

Can we close this issue then?

**Comment by woodyNsinbad** [comment]
> Glad you have it working. We also added a PR to make the possible error more clear, see #2932, I still suspect your error is due to a lack of `cmake` and `git` which neither of these Docker containers has by default. It so happens that I am the author of the Docker r-base container, and the rocker/r2u container. I can only reiterate that you may want to have a look at [r2u](https://eddelbuettel.github.io/r2u). But of course -- if you prefer mamba that works as well.
> 
> Can we close this issue then?

yes, thanks again.
