### ISSUE TITLE
[python/ci] Investigate recent CI failure

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#3246]
Recent CI jobs are failing with typeguard-related errors. Examples:

* https://github.com/single-cell-data/TileDB-SOMA/pull/3244
* https://github.com/TileDB-Inc/centralized-tiledb-nightlies/issues/25

As an experiment I took a recent merge to `main` and simply re-ran it with zero code mods:

* https://github.com/single-cell-data/TileDB-SOMA/actions/runs/11522767244/job/32079325840
* https://github.com/single-cell-data/TileDB-SOMA/actions/runs/11522767244/job/32157898699

The only diffs I could find by log-diffing were `pyarrow` 17 vs 18, which I've ruled out via #3245; also `typeguard` 4.4.0 recently came out and I don't believe that's the problem either but I'll verify.

[[sc-58398]](https://app.shortcut.com/tiledb-inc/story/58398/investigate-recent-ci-failure)

**Comment by ryan-williams** [comment]
`main` [is green](https://github.com/single-cell-data/TileDB-SOMA/actions/runs/11556516471) again as of #3247.

Pinning to a specific typeguard SHA should be reasonably stable, though not ideal "long-term." I'll look into the actual issue a bit more, it may require a small change in Typeguard. 

https://github.com/single-cell-data/TileDB-SOMA/issues/3216 may be the best place for follow-up, and close this since CI is OK again?
