### ISSUE TITLE
[python] Initial stateful Python implementation

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#603]
Make the API stateful, so it can represent an explicit point-in-time handle to a durable collection and/or object.

#540 tracks the full gamut of statefulness:

* Right now: open all arrays with time.now() timestamp (implcitly)
* Sooner:
  * `experiment.open()` with implicit `time.now()` put into some variable/config/something
  * All component opens will use that timestamp
* Easy to do after:
  * `experiment.open(specified_timestamp)`
  * All component opens will use that timestamp
* More after that:
  * Grouped commit / fragment coalesce / rollback ideas 

This issue is specifically about moving from the first bullet (the status quo) to the second bullet.
 
Follow-on from https://github.com/single-cell-data/SOMA/issues/44

**Comment by maniarathi** [comment]
@mlin @thetorpedodog Is this complete? Can we close this issue?

**Comment by thetorpedodog** [comment]
Going over why we marked this done:

We're currently passing around the `context` object every time we open (and soon, when we create) a SOMA object from a parent. This is where we are sticking the timestamp to support consistency.

Further work includes finishing out the `add_new_x` methods (https://github.com/single-cell-data/TileDB-SOMA/issues/840), and making it so that when we do open child objects their ownership is tracked for closing them all (https://github.com/single-cell-data/TileDB-SOMA/issues/843).

**Comment by thetorpedodog** [comment]
And @mlin is working on timestamp setting in https://github.com/single-cell-data/TileDB-SOMA/pull/819, which I stomped all over in https://github.com/single-cell-data/TileDB-SOMA/commit/93050f1ca76700b6038033befe953b6f6085bee0.
